apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongodb
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: <REPLACE-WITH-HOST> # Required unless "server" field is set . Example: "mongo-mongodb.default.svc.cluster.local:27017"
  - name: username
    value: <REPLACE-WITH-USERNAME> # Optional. Example: "admin"
  - name: password
    value: <REPLACE-WITH-PASSWORD> # Optional.
  - name: databaseName
    value: <REPLACE-WITH-DATABASE-NAME> # Optional. default: "daprStore"
  # - name: collectionName
  #   value: <REPLACE-WITH-COLLECTION-NAME> # Optional. default: "daprCollection"
  