apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: assetAnalyzer
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis_service:6379
    - name: redisPassword
      secretKeyRef:
        name: redisPassword
        key: redisPassword
auth:
  secretStore: localsecrets
