version: '3.7'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=${SPARK_MASTER_NODE_MODE}
      - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_MASTER_NODE_RPC_AUTHENTICATION_ENABLED}
      - SPARK_RPC_ENCRYPTION_ENABLED=${SPARK_MASTER_NODE_RPC_ENCRYPTION_ENABLED}
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=${SPARK_MASTER_NODE_LOCAL_STORAGE_ENCRYPTION_ENABLED}
      - SPARK_SSL_ENABLED=${SPARK_MASTER_NODE_SSL_ENABLED}
    ports:
      - '${SPARK_MASTER_NODE_PUBLIC_PORT}:${SPARK_MASTER_NODE_PORT}'
    env_file:
      - ./.env

  spark-worker-a:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-a
    environment:
      - SPARK_MODE=${SPARK_WORKER_1_MODE}
      - SPARK_MASTER_URL=${SPARK_WORKER_1_MASTER_URL}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_1_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_1_WORKER_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_WORKER_1_RPC_AUTHENTICATION_ENABLED}
      - SPARK_RPC_ENCRYPTION_ENABLED=${SPARK_WORKER_1_RPC_ENCRYPTION_ENABLED}
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=${SPARK_WORKER_1_LOCAL_STORAGE_ENCRYPTION_ENABLED}
      - SPARK_SSL_ENABLED=${SPARK_WORKER_1_SSL_ENABLED}
    env_file:
      - ./.env

  spark-worker-b:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-b
    environment:
      - SPARK_MODE=${SPARK_WORKER_2_MODE}
      - SPARK_MASTER_URL=${SPARK_WORKER_2_MASTER_URL}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_2_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_2_WORKER_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_WORKER_2_RPC_AUTHENTICATION_ENABLED}
      - SPARK_RPC_ENCRYPTION_ENABLED=${SPARK_WORKER_2_RPC_ENCRYPTION_ENABLED}
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=${SPARK_WORKER_2_LOCAL_STORAGE_ENCRYPTION_ENABLED}
      - SPARK_SSL_ENABLED=${SPARK_WORKER_2_SSL_ENABLED}
    env_file:
      - ./.env

networks:
  default:
    name: asset_analyzer_network
    driver: bridge
