apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: assetAnalyzerDaprConfig
  namespace: assetAnalyzer
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin_service:9411/api/v2/spans"
  metric:
    enabled: true
