version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:latest
    # container_name: miniflux
    ports:
      - "${MINIFLUX_PUBLIC_PORT}:${MINIFLUX_INTERNAL_PORT}"
    depends_on:
      - miniflux-db
    environment:
      DATABASE_URL: ${MINIFLUX_DATABASE_URL}
      RUN_MIGRATIONS: ${MINIFLUX_RUN_MIGRATIONS}
      CREATE_ADMIN: ${MINIFLUX_CREATE_ADMIN}
      ADMIN_USERNAME: ${MINIFLUX_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${MINIFLUX_ADMIN_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    networks:
      - asset_analyzer_network

  miniflux-db:
    image: postgres:15
    # container_name: miniflux-db
    ports:
      - "${MINIFLUX_DB_PUBLIC_PORT}:${MINIFLUX_DB_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: ${MINIFLUX_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MINIFLUX_DB_POSTGRES_PASSWORD}
      # POSTGRES_DB: ${MINIFLUX_DB_POSTGRES_DB}
    volumes:
      - ./data/miniflux-db:/var/lib/postgresql/data
      - ./conf/miniflux_db/db.conf:/etc/postgresql/postgresql.conf
      - ./conf/miniflux_db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    env_file:
      - ./.env
    command: ['-c', 'config_file=/etc/postgresql/postgresql.conf']
    networks:
      - asset_analyzer_network
